pull_request_rules:
  - name: automatic merge when CI passes, 1 review, and 1 label
    conditions:
      - base=master
      - label=merge
      - label!=blocked
    actions:
      merge:
        method: squash
        strict: smart
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: automatic update HEAD
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
        strict: true
