pull_request_rules:
  - name: Auto Merge: "merge" label and Conventional Commits tags
    conditions:
      - base=master
      - label=merge
      - label!=blocked
      - title~=^[fix|feat|chore|perf].*
    actions:
      merge:
        method: squash
        strict: smart
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
