pull_request_rules:
  - name: automatic merge when CI passes, 1 review, and 1 label
    conditions:
      - base=master
      - label=merge
      - label!=blocked
      - base=master
    actions:
      merge:
        method: squash
        strict: smart