pull_request_rules:
  - name: automatic merge when CI passes, 1 review, and 1 label
    conditions:
      - "#approved-reviews-by>=2"
      - status-success=Travis CI - Pull Request
      - base=master
      - label=[merge]
      - label!=[blocked]
    actions:
      merge:
        method: squash
        strict: smart