language: node_js
node_js: '8.11.2'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
    # Fix intermittent "resource temporarily unavailable" and "write" errors failing the Travis builds.
    # See: https://github.com/travis-ci/travis-ci/issues/8920
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
stages:
  - name: Test
    if: (type IN (pull_request)) OR (type IN (push) AND branch = master)
  - name: Deploy Api
    if: (type IN (push) AND branch = master)
jobs:
  include:
    - stage: Test
      script:
        - yarn lint
    - script:
        - travis_wait yarn ci-test
        - travis_wait yarn codecov
    - stage: Deploy Api
      script: skip
      before_deploy: npm install -g now
      deploy:
        - provider: script
          script: echo "Deploying via Github hooks"
          skip_cleanup: true
          master: true
