language: node_js
node_js: '8.11.2'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
install:
  - bash ./scripts/install-yarn-dependencies.sh
stages:
  - name: test
    if: (type IN (pull_request)) OR (type IN (push) AND branch = master)
jobs:
  include:
    - stage: test
      script:
        - bash ./scripts/global-npm-script.sh lint
    - script:
        - travis_wait bash ./scripts/global-npm-script.sh test "travis" && bash ./scripts/global-npm-script.sh codecov
before_deploy: npm install now --no-save
deploy:
  - provider: script
    script: cd api && now --token --public $NOW_TOKEN && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
