language: node_js
node_js: '8.11.2'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
install:
  - bash ./scripts/install-yarn-dependencies.sh
stages:
  - name: Test
    if: (type IN (pull_request)) OR (type IN (push) AND branch = master)
  - name: Deploy Api
    if: (type IN (push) AND branch = master)
jobs:
  include:
    - stage: Test
      script:
        - bash ./scripts/global-npm-script.sh lint
    - script:
        - travis_wait bash ./scripts/global-npm-script.sh test "travis" && bash ./scripts/global-npm-script.sh codecov
    - stage: Deploy Api
      script: skip
      before_deploy: npm install -g now
      deploy:
        - provider: script
          script: cd api && now --public --team Apolloschurch --token $NOW_TOKEN && now alias --team Apolloschurch --token $NOW_TOKEN && now rm apollos-church-api --team Apolloschurch --safe --yes --token $NOW_TOKEN
          skip_cleanup: true
          master: true
