language: node_js
node_js: '8.11.2'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
    # Fix intermittent "resource temporarily unavailable" and "write" errors failing the Travis builds.
    # See: https://github.com/travis-ci/travis-ci/issues/8920
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
stages:
  - name: Test
    if: (type IN (pull_request)) OR (type IN (push) AND branch = master)
  - name: Schema Diff
    if: (type IN (pull_request)) OR (type IN (push) AND branch = master)
  - name: Deploy Api
    if: (type IN (push) AND branch = master)
  - name: NPM Release
    if: (type IN (push) AND branch = master)
  - name: Deploy Docs
    if: (type IN (push) AND branch = master)
jobs:
  include:
    - stage: Test
      script:
        - yarn lint
    - script:
        - travis_wait yarn ci-test
        - travis_wait yarn codecov
    - stage: Deploy Api
      script: skip
      deploy:
        - provider: script
          script: echo "Deploying via Github hooks"
          skip_cleanup: true
          master: true
    - stage: NPM Release
      script: yarn lerna run build
      before_deploy:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
      deploy:
        provider: script
        script: yarn release:canary
        skip_cleanup: true
        master: true
    - stage: Deploy Docs
      script:
        - yarn generate-docs
        - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
        - git clone git://${GH_DOCS_REPO}
        - cp -fr packages/apollos-ui-kit/docs/generated/* docs/docs/ui-kit
        - cd packages/apollos-ui-kit
        - cat ../../docs/website/sidebars.json | docs/updateSidebar.sh
        - cd ../../
        - cp -f packages/apollos-ui-kit/docs/generated/sidebars.json docs/website/sidebars.json
        - cd docs
        - git remote
        - git config user.email ${GH_EMAIL}
        - git config user.name ${GH_USER}
        - git add .
        - git diff-index --quiet HEAD -- || git commit -am "${MESSAGE}"
        - git push "https://${GH_TOKEN}@${GH_DOCS_REPO}" master
