coverage:
  status:
    project:
      api:
        paths:
          - packages/apollos-church-api/*
          - packages/apollos-rock-apollo-data-source/*
      mobile:
        paths:
          - packages/apolloschurchapp/*
comment:
  layout: "reach, diff, files"
  behavior: once
