name: Publish Canary

on:
  push:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node 10.19.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.19.x

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install Dependencies
      run: yarn

    - name: Canary Release
      run: |
        echo "registry=https://npm.pkg.github.com/apollosproject" >> .npmrc
        yarn release:canary
