name: Publish Canary

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.19.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn

    - name: Install Dependencies
      run: yarn

    - name: Canary Release
      run:
        - echo "registry=https://npm.pkg.github.com/apollosproject" >> .npmrc
        - yarn release:canary
